# Generated by Django 3.2.13 on 2022-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('address', models.TextField(default='HouseNo ,Builidng,Street,Area *', max_length=100)),
                ('locality', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
                ('type_of_address', models.CharField(choices=[('H', 'Home'), ('O', 'Office')], max_length=20)),
            ],
        ),
    ]
