# Generated by Django 3.2.13 on 2022-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type_of_address',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], max_length=20),
        ),
    ]
